{% set version = "8.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-boruta
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Boruta_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Boruta/Boruta_{{ version }}.tar.gz
  sha256: 38e75b1ebc8b2d1c54b3373a42529b819c7b4773fd4932f57bc9701d1e3e3dc7

build:
  noarch: generic
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-ranger
  run:
    - r-base
    - r-ranger

test:
  commands:
    - $R -e "library('Boruta')"           # [not win]
    - "\"%R%\" -e \"library('Boruta')\""  # [win]

about:
  home: https://notabug.org/mbq/Boruta/
  license: GPL-2.0-or-later
  summary: An all relevant feature selection wrapper algorithm. It finds relevant features by comparing original attributes' importance with importance achievable at random, estimated using their permuted copies (shadows).
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - nick-youngblut
