{% set version = '6.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-boruta
  version: {{ version|replace("-", "_") }}

source:
  fn: Boruta_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/Boruta_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Boruta/Boruta_{{ version }}.tar.gz
  sha256: 1c9a7aabe09f040e147f6c614f5fe1d0b951d3b0f0024161fbb4c31da8fae8de

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-ranger
  run:
    - r-base
    - r-ranger

test:
  commands:
    - $R -e "library('Boruta')"           # [not win]
    - "\"%R%\" -e \"library('Boruta')\""  # [win]

about:
  home: https://notabug.org/mbq/Boruta/
  license: GPL (>= 2)
  summary: An all relevant feature selection wrapper algorithm. It finds relevant features by
    comparing original attributes' importance with importance achievable at random,
    estimated using their permuted copies (shadows).
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
