appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: q9Ri2fi7q+aL2yLtPikr/Q9EWkpJt/DPonzfV2a9K74+piaFvkgiX0RaSTV+3eWAIslKYWhlKslFivcZpyMcRBubqV/fHX1k9b7rxy6hp+uOLobXHY9n9dF1Ya5xpJkoBfxhKyjYBhbzDq2uKprdUql+fUFdWoP+WnO0X06VXUF4YX2D7RB39Beh+OlM6alegGAhotome46qRvkx95xRVNW8kTeNrXHZ4yy8q5vEjBz+dCN1dFJLmJCqVxHn/o8H2l5jt7/J8H5a6dn8mYUN6/VBRSdQq7qolqxtFlVg/sFFhAxz/6hXW30F6jip4GiH6GZgSPrOKJ+4QpM34w1Mst71YJDT2EcuVX+v7FCy6R31XjqPtPUMggd+Y/qcbpKADSRq+FiRnwJiDMzWGOMCWxYKrdXAdEwIhh38FM6ZXzfMGNS5/PQYqVJmSmeYL66GJxMMVASj8VZHMVxrF1yDSZzY/QmQf6inDAg75u5PdSkE2/T/ZlKmgfV81gC7A0bgxZnaUfBGkPZvcBfUeSVZ5I6uYv8W/mKAuTKj2bvR8HLpIwf0ABtayLWtNyQIG9bNRkZEJWcwiHcE3JUtfEPeW+2HS++7qpT53fZlczSPcZnH06zDszD1ntCGhlHT6wTRNg37qwHA+7FZjH5JLEmGe9lEIdOcqg+Z01i7mivgQwA=}
