travis:
  secure:
    BINSTAR_TOKEN: Tik1Y/jq3gyzjXNN+EGUU9Mxk152+MzdkrSSgOeHCKS8xU3aaf/mznQE42KR2HuStTnQdyXU0TmPXnhsuCNPvyUqiRYspEw2CxV8jP/1TAznzkdaw1xAm7SCzKM7HynkCLf4gsZq46uwqhe3D3xEZA8sqaAHJ9z22xDqIhNhZ06h80QuxEnCejSnRnZJHlPOVzWsOM5hx3jBQFVuuSDzKwJU9RDuR1XSR8SOK+3nbddrmCmMdK21E0BfolBKHh1FpT7Sg+vgburMXsycKY+EbbhQSHsyZzZHRznr5JE7zZQ4z5G6nHo+skKWfBQxaMbXJBysxOIP9Ip0qLtJ+yiW9RGpkD4j3DqOspRagz2IVF6keuKcmtLvKaaC+hKUOd3p8d4d4OkQXH+oawE77WhOcZT202mkvfgQp2+DFIT4+M63eCUeiNR/rEVACNBq66gtnAo115u4MAw7XKZVmBUHokKXZcn0r6R6OLxRCbdOMFdbw/HSz27z5R6N9nQVuG5rXysK55MxjWrk6iFd91n6iJo9sLlfB28npZMDaKWCTy5epRzMf1R9+Tb5FKmO2KvVH1EgSZwwqXV7xQCTxRywUUAFSuOqRDsHilx3RsJqqetHZVrFiJ0NZRqyahci78hSRfA9JOAWovZ6sQ/7MC6W0+B76aZR+gwXlyYmfrkJU/w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
